# Generated by Django 5.0 on 2024-10-10 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resettoken',
            name='expire_at',
        ),
    ]
