# Generated by Django 5.0 on 2024-10-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_remove_resettoken_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resettoken',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
